### ISSUE TITLE
Test reporter that only displays failed tests

### ISSUE THREAD

**Issue by AmaranthineCodices** [Roblox/testez#17]
It'd be really nice to have a reporter similar to `TextReporter` that only prints the specific tests that failed. This would make it a lot easier to see test failures in projects where there are a lot of tests.

**Comment by LPGhatguy** [comment]
I want to revamp the reporter system to make them plain old functions, as well as make the data more inspectable so that having a user feature like this is reasonable!

Definitely want this in TestEZ itself, too. The other thing I want it to do is capture + report errors inline with the test so that it's obvious which error came from which test.

**Comment by LPGhatguy** [comment]
Closed by b07bc592ddeb0f1d71b78ade32e5cbd4a78b6bb8.
